services:
  - type: web
    name: smartcart-backend
    env: python
    pythonVersion: 3.11.6        # forces Python 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true